// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBri8BEHRaNwVpJd60vKyDBp8qqbAeL8ns',
    appId: '1:94439190209:web:ed22331ae3f3275862ae40',
    messagingSenderId: '94439190209',
    projectId: 'fir-app-fd532',
    authDomain: 'fir-app-fd532.firebaseapp.com',
    storageBucket: 'fir-app-fd532.appspot.com',
    measurementId: 'G-LPFE2MG5GL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDud3eSfjAspoxuhHjxPOXtnWv6hHpDBbU',
    appId: '1:94439190209:android:90799cb40be380b762ae40',
    messagingSenderId: '94439190209',
    projectId: 'fir-app-fd532',
    storageBucket: 'fir-app-fd532.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB13ELDBn9VSEPQmK12ixgnqON9KH_UGQ',
    appId: '1:94439190209:ios:27f63a245e5f100a62ae40',
    messagingSenderId: '94439190209',
    projectId: 'fir-app-fd532',
    storageBucket: 'fir-app-fd532.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB13ELDBn9VSEPQmK12ixgnqON9KH_UGQ',
    appId: '1:94439190209:ios:da7ca05de6ed2f7862ae40',
    messagingSenderId: '94439190209',
    projectId: 'fir-app-fd532',
    storageBucket: 'fir-app-fd532.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
